# Generated by Django 5.2.10 on 2026-01-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="선수명")),
                ("team", models.CharField(max_length=50, verbose_name="팀명")),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("pitcher", "투수"),
                            ("catcher", "포수"),
                            ("first", "1루수"),
                            ("second", "2루수"),
                            ("shortstop", "유격수"),
                            ("third", "3루수"),
                            ("left", "좌익수"),
                            ("center", "중견수"),
                            ("right", "우익수"),
                        ],
                        max_length=20,
                        verbose_name="포지션",
                    ),
                ),
                ("back_number", models.IntegerField(verbose_name="등번호")),
                (
                    "batting_average",
                    models.FloatField(blank=True, null=True, verbose_name="타율"),
                ),
                (
                    "home_runs",
                    models.IntegerField(blank=True, null=True, verbose_name="홈런"),
                ),
                ("rbis", models.IntegerField(blank=True, null=True, verbose_name="타점")),
                ("era", models.FloatField(blank=True, null=True, verbose_name="평균자책점")),
                ("wins", models.IntegerField(blank=True, null=True, verbose_name="승")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
            ],
            options={
                "verbose_name": "선수",
                "verbose_name_plural": "선수들",
                "db_table": "players",
                "ordering": ["position", "back_number"],
            },
        ),
    ]
